In [1]:
import numpy as np
import pandas as pd
import os
import sys

In [2]:
# Setting path to load util functions
from pathlib import Path
parent_dir = Path.cwd().parents[1]
sys.path.append(os.path.abspath(parent_dir))

In [ ]:
def load_data(data_path, file_type = 'parquet'):
    """
    Load the data from the specified path.
    """
    if file_type == 'parquet':
        df = pd.read_parquet(data_path)
    else:
        df = pd.read_csv(data_path)
    df['S_2'] = pd.to_datetime(df['S_2'])
    df['end_of_month'] = df['S_2'] + pd.offsets.MonthEnd(0)

    return df

In [3]:
df = pd.read_parquet('../../data/train_data.parquet')
df['S_2'] = pd.to_datetime(df['S_2'])

In [4]:
df['end_of_month'] = df['S_2'] + pd.offsets.MonthEnd(0)

In [5]:
df.head()['customer_ID'].values

array(['0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a',
       '0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a',
       '0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a',
       '0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a',
       '0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a'],
      dtype=object)

In [6]:
one_id_df = df[df['customer_ID'].isin(['0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a'])]

In [7]:
del df

In [8]:
one_id_df.head()

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,target,end_of_month
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0.001733,0.008724,1.006838,0.009228,0.124035,0.008771,0.004709,...,NaN,0.002427,0.003706,0.003818,NaN,0.000569,0.000610,0.002674,0,2017-03-31
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0.005775,0.004923,1.000653,0.006151,0.126750,0.000798,0.002714,...,NaN,0.003954,0.003167,0.005032,NaN,0.009576,0.005492,0.009217,0,2017-04-30
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,0.091505,0.021655,1.009672,0.006815,0.123977,0.007598,0.009423,...,NaN,0.003269,0.007329,0.000427,NaN,0.003429,0.006986,0.002603,0,2017-05-31
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0.002455,0.013683,1.002700,0.001373,0.117169,0.000685,0.005531,...,NaN,0.006117,0.004516,0.003200,NaN,0.008419,0.006527,0.009600,0,2017-06-30
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0.002483,0.015193,1.000727,0.007605,0.117325,0.004653,0.009312,...,NaN,0.003671,0.004946,0.008889,NaN,0.001670,0.008126,0.009827,0,2017-07-31

In [ ]:
from utils.inference_helpers import backfill_null_values
def filter_and_impute_df(df):

    non_null_cols = pd.read_csv('../../utils/selected_features/non_null_cols_filter.csv')['Feature'].values
    df = df[non_null_cols]

    cat_cols = ['D_126', 'D_63']
    one_id_df[cat_cols] = one_id_df[cat_cols].astype('category')

    df = backfill_null_values(df, columns=None, group_by='customer_ID')

    return df

In [9]:
non_null_cols = pd.read_csv('../../utils/selected_features/non_null_cols_filter.csv')['Feature'].values
one_id_df = one_id_df[non_null_cols]

In [53]:
non_null_cols

array(['customer_ID', 'S_2', 'D_39', 'B_1', 'R_1', 'B_4', 'B_5', 'R_2',
       'D_47', 'B_7', 'D_51', 'B_9', 'R_3', 'B_10', 'S_5', 'B_11', 'S_6',
       'R_4', 'B_12', 'S_8', 'R_5', 'D_58', 'B_14', 'D_60', 'S_11',
       'D_63', 'D_65', 'B_18', 'S_12', 'R_6', 'S_13', 'B_21', 'D_71',
       'S_15', 'B_23', 'P_4', 'D_75', 'B_24', 'R_7', 'R_8', 'S_16',
       'R_10', 'R_11', 'S_17', 'R_12', 'B_28', 'R_13', 'R_14', 'R_15',
       'R_16', 'S_18', 'D_86', 'R_17', 'R_18', 'B_31', 'S_19', 'R_19',
       'B_32', 'S_20', 'R_20', 'R_21', 'R_22', 'R_23', 'D_92', 'D_93',
       'D_94', 'R_24', 'R_25', 'D_96', 'S_26', 'D_102', 'B_36', 'B_37',
       'B_40', 'D_126', 'D_127', 'B_41', 'D_133', 'R_28', 'D_140',
       'D_144', 'target', 'end_of_month'], dtype=object)

In [10]:
one_id_df.shape

(13, 83)

In [11]:
one_id_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 12
Data columns (total 83 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_ID   13 non-null     object
 1   S_2           13 non-null     datetime64[ns]
 2   D_39          13 non-null     float32
 3   B_1           13 non-null     float32
 4   R_1           13 non-null     float32
 5   B_4           13 non-null     float32
 6   B_5           13 non-null     float32
 7   R_2           13 non-null     float32
 8   D_47          13 non-null     float32
 9   B_7           13 non-null     float32
 10  D_51          13 non-null     float32
 11  B_9           13 non-null     float32
 12  R_3           13 non-null     float32
 13  B_10          13 non-null     float32
 14  S_5           13 non-null     float32
 15  B_11          13 non-null     float32
 16  S_6           13 non-null     float32
 17  R_4           13 non-null     float32
 18  B_12          13 non-null     float32
 19  S_8           13 non-null     float32
 20  R_5           13 non-null     float32
 21  D_58          13 non-null     float32
 22  B_14          13 non-null     float32
 23  D_60          13 non-null     float32
 24  S_11          13 non-null     float32
 25  D_63          13 non-null     object
 26  D_65          13 non-null     float32
 27  B_18          13 non-null     float32
 28  S_12          13 non-null     float32
 29  R_6           13 non-null     float32
 30  S_13          13 non-null     float32
 31  B_21          13 non-null     float32
 32  D_71          13 non-null     float32
 33  S_15          13 non-null     float32
 34  B_23          13 non-null     float32
 35  P_4           13 non-null     float32
 36  D_75          13 non-null     float32
 37  B_24          13 non-null     float32
 38  R_7           13 non-null     float32
 39  R_8           13 non-null     float32
 40  S_16          13 non-null     float32
 41  R_10          13 non-null     float32
 42  R_11          13 non-null     float32
 43  S_17          13 non-null     float32
 44  R_12          13 non-null     float32
 45  B_28          13 non-null     float32
 46  R_13          13 non-null     float32
 47  R_14          13 non-null     float32
 48  R_15          13 non-null     float32
 49  R_16          13 non-null     float32
 50  S_18          13 non-null     float32
 51  D_86          13 non-null     float32
 52  R_17          13 non-null     float32
 53  R_18          13 non-null     float32
 54  B_31          13 non-null     int64
 55  S_19          13 non-null     float32
 56  R_19          13 non-null     float32
 57  B_32          13 non-null     float32
 58  S_20          13 non-null     float32
 59  R_20          13 non-null     float32
 60  R_21          13 non-null     float32
 61  R_22          13 non-null     float32
 62  R_23          13 non-null     float32
 63  D_92          13 non-null     float32
 64  D_93          13 non-null     float32
 65  D_94          13 non-null     float32
 66  R_24          13 non-null     float32
 67  R_25          13 non-null     float32
 68  D_96          13 non-null     float32
 69  S_26          13 non-null     float32
 70  D_102         13 non-null     float32
 71  B_36          13 non-null     float32
 72  B_37          13 non-null     float32
 73  B_40          13 non-null     float32
 74  D_126         13 non-null     float32
 75  D_127         13 non-null     float32
 76  B_41          13 non-null     float32
 77  D_133         13 non-null     float32
 78  R_28          13 non-null     float32
 79  D_140         13 non-null     float32
 80  D_144         13 non-null     float32
 81  target        13 non-null     int64
 82  end_of_month  13 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float32(77), int64(2), object(2)
memory usage: 4.6+ KB

In [12]:
cat_cols = ['D_126', 'D_63']
one_id_df[cat_cols] = one_id_df[cat_cols].astype('category')

In [13]:
from utils.inference_helpers import backfill_null_values
one_id_df = backfill_null_values(one_id_df, columns=None, group_by='customer_ID')

In [ ]:
import pickle
def encode_df(df):
    """
    Encode the categorical columns in the dataframe.
    """
    cat_encoder = pickle.load(open('../../utils/encoders/categorical_encoder.pkl', 'rb'))

    df = pd.concat([df.drop(columns=cat_encoder.feature_names_in_),
                       pd.DataFrame(cat_encoder.transform(df[cat_encoder.feature_names_in_]),
                                    columns=cat_encoder.get_feature_names_out(),index=df.index)], axis=1)
    
    return df

In [ ]:
#load categorical encoder
import pickle
cat_encoder = pickle.load(open('../../utils/encoders/categorical_encoder.pkl', 'rb'))

In [16]:
one_id_df = pd.concat([one_id_df.drop(columns=cat_encoder.feature_names_in_),
                       pd.DataFrame(cat_encoder.transform(one_id_df[cat_encoder.feature_names_in_]),
                                    columns=cat_encoder.get_feature_names_out(),index=one_id_df.index)], axis=1)

In [17]:
one_id_df.shape

(13, 91)

In [ ]:
#tsfel
def get_imp_cols_append(file_path):
    """
    Function to get the columns to append from the file path
    """
    cols_to_append = pd.read_csv(file_path)
    cols_to_append = cols_to_append[cols_to_append['Importance'] == 1]['Feature'].values
    cols_to_append = np.append(['customer_ID', 'end_of_month'], cols_to_append)

    return cols_to_append

In [ ]:
from utils.TimeSeriesFeatureCreation import TimeSeriesFeatureCreation
def create_ts_features(df, select_date = '2018-03-31'):
    '''
    Function to create time series features using the TimeSeriesFeatureCreation class
    and select data and impute null values
    '''

    ts_creator = TimeSeriesFeatureCreation(create_2_diff=False, verbose = False, id_col='customer_ID', date_col = 'end_of_month',
                                       rolling_window_size=6, span = 6, num_lags=3)
    
    cols_to_append = get_imp_cols_append('../../utils/selected_features/ts_features_boruta.csv')

    df = ts_creator.transform(df[cols_to_append])
    df = df[df['end_of_month'] == select_date]

    ts_feat = pd.read_csv('../../utils/selected_features/ts_features_boruta.csv')
    ts_feat_cols = ts_feat[ts_feat['Importance'] == 1]['Feature'].values
    ts_feat_cols = np.append(['customer_ID'], ts_feat_cols)

    df_ts = df[ts_feat_cols]
    df_ts = df_ts.fillna(0)

    return df_ts

In [19]:
ts_creator = TimeSeriesFeatureCreation(create_2_diff=False, verbose = False, id_col='customer_ID', date_col = 'end_of_month',
                                       rolling_window_size=6, span = 6, num_lags=3)

In [20]:
selected_features = pd.read_csv('../../utils/selected_features/boruta_features_baseline.csv')
selected_features = selected_features[selected_features['Importance'] == 1]['Feature'].values

In [21]:
cols_to_append = ['customer_ID', 'end_of_month']
cols_to_append = np.append(cols_to_append, selected_features)
cols_to_append

array(['customer_ID', 'end_of_month', 'D_63_CL', 'B_14', 'D_60', 'S_11',
       'D_65', 'B_18', 'R_6', 'S_13', 'D_71', 'S_15', 'B_23', 'D_58',
       'P_4', 'R_10', 'R_11', 'R_12', 'B_28', 'R_16', 'S_26', 'D_102',
       'B_37', 'B_40', 'D_133', 'D_75', 'R_5', 'B_24', 'B_12', 'D_63_CO',
       'D_63_CR', 'S_8', 'D_126_1.0', 'D_39', 'B_1', 'R_1', 'B_4', 'B_5',
       'R_2', 'D_47', 'D_144', 'D_51', 'B_11', 'S_5', 'R_3', 'B_9',
       'B_10', 'R_4', 'B_7'], dtype=object)

In [22]:
one_id_df_ts = ts_creator.transform(one_id_df[cols_to_append])

Aggregated DataFrame type: <class 'pandas.core.frame.DataFrame'>

Creating time series features for each feature: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 47/47 [00:00<00:00, 115.95it/s]

Concatenating 282 feature DataFrames.

In [23]:
one_id_df_ts = one_id_df_ts[one_id_df_ts['end_of_month'] == '2018-03-31']

In [24]:
ts_feat = pd.read_csv('../../utils/selected_features/ts_features_boruta.csv')
ts_feat_cols = ts_feat[ts_feat['Importance'] == 1]['Feature'].values

In [25]:
ts_feat_cols = np.append(['customer_ID'], ts_feat_cols)

In [26]:
one_id_df_ts = one_id_df_ts[ts_feat_cols]

In [27]:
one_id_df.isna().sum().sum()

0

In [ ]:
import tsfel
from utils.inference_helpers import extract_tsfel_features_joblib_optimized

def create_tsfel_features(df):
    cfg = tsfel.get_features_by_domain(domain=['temporal', 'statistical'])

    cols_to_append = get_imp_cols_append('../../utils/selected_features/boruta_features_baseline.csv')

    df_tsfel = extract_tsfel_features_joblib_optimized(
        df[cols_to_append],
        customer_id_col='customer_ID',
        timestamp_col='end_of_month',
        features_to_extract=cfg,
        n_jobs=-1, # Use all cores
        verbose=0 # Set verbosity for progress updates and ETA
    )

    stat_select = pd.read_csv('../../utils/selected_features/tsfel_stat_features_boruta.csv')
    temporal_select = pd.read_csv('../../utils/selected_features/tsfel_temporal_features_boruta.csv')

    stat_select_cols = stat_select[stat_select['Importance'] == 1]['Feature'].values
    temporal_select_cols = temporal_select[temporal_select['Importance'] == 1]['Feature'].values

    tsfel_cols = np.append(stat_select_cols, temporal_select_cols)
    df_tsfel = df_tsfel[tsfel_cols]
    df_tsfel.reset_index(drop=False, inplace=True)
    
    df_tsfel = df_tsfel.fillna(0)

    return df_tsfel

In [29]:
import tsfel

In [30]:
cfg = tsfel.get_features_by_domain(domain=['temporal', 'statistical'])

In [31]:
from utils.inference_helpers import extract_tsfel_features_joblib_optimized

In [32]:
one_id_df_tsfel = extract_tsfel_features_joblib_optimized(
        one_id_df[cols_to_append],
        customer_id_col='customer_ID',
        timestamp_col='end_of_month',
        features_to_extract=cfg,
        n_jobs=-1, # Use all cores
        verbose=0 # Set verbosity for progress updates and ETA
    )

# --- Display Results ---
print("\n--- Extracted Features (Optimized Joblib Method + Verbose Progress) ---")
if not one_id_df_tsfel.empty:
    print(f"Shape: {one_id_df_tsfel.shape}")
    try:
        display(one_id_df_tsfel.head())
    except NameError:
        print(one_id_df_tsfel.head())
else:
    print("Resulting DataFrame is empty.")

Input shape: (13, 49), Grouping by: customer_ID, Timestamp: end_of_month
Using provided TSFEL configuration dictionary.
Processing 1 customer groups...
Setting up Joblib with 20 processes (verbose=0)...

Joblib parallel processing finished in 2.75 seconds.
Successfully processed 1 out of 1 groups.
Preparing results for concatenation...
Concatenating reindexed results...
Concatenation complete.
Robust concatenation finished in 0.19 seconds.
Final features DataFrame shape: (1, 2115)

--- Extracted Features (Optimized Joblib Method + Verbose Progress) ---
Shape: (1, 2115)

,B_10_Absolute energy,B_10_Area under the curve,B_10_Autocorrelation,B_10_Average power,B_10_Centroid,B_10_ECDF Percentile Count_0,B_10_ECDF Percentile Count_1,B_10_ECDF Percentile_0,B_10_ECDF Percentile_1,B_10_ECDF_0,...,S_8_Peak to peak distance,S_8_Positive turning points,S_8_Root mean square,S_8_Signal distance,S_8_Skewness,S_8_Slope,S_8_Standard deviation,S_8_Sum absolute diff,S_8_Variance,S_8_Zero crossing rate
customer_ID,,,,,,,,,,,,,,,,,,,,,
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,1.346612,0.033025,3.0,11.221769,0.089401,2.0,10.0,0.099804,0.325464,0.076923,...,0.513746,3.0,0.80783,12.128874,-0.529305,-0.025907,0.130957,1.143922,0.01715,0.0

In [33]:
stat_select = pd.read_csv('../../utils/selected_features/tsfel_stat_features_boruta.csv')
temporal_select = pd.read_csv('../../utils/selected_features/tsfel_temporal_features_boruta.csv')

In [34]:
stat_select_cols = stat_select[stat_select['Importance'] == 1]['Feature'].values
temporal_select_cols = temporal_select[temporal_select['Importance'] == 1]['Feature'].values

In [35]:
len(stat_select_cols), len(temporal_select_cols)

(137, 101)

In [36]:
tsfel_cols = np.append(stat_select_cols, temporal_select_cols)
# tsfel_cols = np.append(['customer_ID'], tsfel_cols)

In [37]:
one_id_df_tsfel = one_id_df_tsfel[tsfel_cols]

In [38]:
one_id_df_tsfel.reset_index(drop=False, inplace=True)
one_id_df_tsfel

,customer_ID,R_10_Mean absolute deviation,R_5_Max,D_126_1.0_Average power,D_102_Root mean square,B_9_Root mean square,B_9_Max,B_9_Average power,R_5_Histogram mode,B_7_Root mean square,...,S_5_Signal distance,B_14_Mean diff,B_11_Mean diff,S_8_Area under the curve,B_11_Area under the curve,S_8_Centroid,B_1_Area under the curve,B_1_Mean diff,S_26_Area under the curve,S_5_Area under the curve
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.001975,0.00982,108.333333,0.858639,0.00693,0.009535,0.005203,0.001678,0.042871,...,12.002586,-0.000679,0.000624,0.096573,0.000875,0.051362,0.00147,0.000055,0.00162,0.003494

In [39]:
one_id_df_tsfel.isna().sum().sum()

0

In [40]:
one_id_df_tsfel = one_id_df_tsfel.fillna(0)

In [41]:
one_id_df_ts

,customer_ID,reverse_ewm_B_7_6,rolling_std_B_4_6,diff_B_4_10,diff_B_4_9,ewm_D_60_6,diff_B_4_8,diff_B_4_6,diff_B_4_5,diff_B_4_4,...,cumsum_D_63_CO,lag_D_63_CO_2,lag_D_63_CO_1,expanding_min_B_28,diff_B_28_2,ewm_D_51_6,ewm_R_16_6,rolling_mean_R_16_6,cumsum_R_16,ewm_B_10_6
12,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.058425,0.036071,0.001954,0.015163,0.550911,0.031931,0.064185,0.065115,0.05708,...,0.0,0.0,0.0,0.005608,0.079137,0.731084,0.004122,0.003347,0.061615,0.381153

In [ ]:
def combine_dfs(one_month_df, ts_df, tsfel_df):

    ts_df = ts_df.drop(columns=[col for col in one_month_df.columns if col != 'customer_ID' and col in ts_df.columns])

    tsfel_df = tsfel_df.drop(columns=[
        col for col in one_month_df.columns if col != 'customer_ID' and col in tsfel_df.columns
    ])

    # Merge all features into a single DataFrame using the 'customer_ID' column
    merged_df = one_month_df.merge(
        ts_df, on='customer_ID', how='left'
    ).merge(
        tsfel_df, on='customer_ID', how='left'
    )

    cols = pd.read_parquet('../../data/final_features_ml/val_all_features_last_month.parquet').columns
    merged_df = merged_df[cols]
    merged_df = merged_df.fillna(0)

In [42]:
one_id_df_one_month = one_id_df[one_id_df['end_of_month'] == '2018-03-31']
one_id_df_one_month.isna().sum().sum()

0

In [43]:
one_id_df_one_month.shape, one_id_df_tsfel.shape, one_id_df_ts.shape

((1, 91), (1, 239), (1, 124))

In [44]:
# Drop overlapping columns from the second DataFrame before merging
one_id_df_ts = one_id_df_ts.drop(columns=[col for col in one_id_df_one_month.columns if col != 'customer_ID' and col in one_id_df_ts.columns])

one_id_df_tsfel = one_id_df_tsfel.drop(columns=[
    col for col in one_id_df_one_month.columns if col != 'customer_ID' and col in one_id_df_tsfel.columns
])

In [45]:
one_id_df_one_month.shape, one_id_df_tsfel.shape, one_id_df_ts.shape

((1, 91), (1, 239), (1, 104))

In [46]:
one_id_df_ts

,customer_ID,reverse_ewm_B_7_6,rolling_std_B_4_6,diff_B_4_10,diff_B_4_9,ewm_D_60_6,diff_B_4_8,diff_B_4_6,diff_B_4_5,diff_B_4_4,...,cumsum_D_63_CO,lag_D_63_CO_2,lag_D_63_CO_1,expanding_min_B_28,diff_B_28_2,ewm_D_51_6,ewm_R_16_6,rolling_mean_R_16_6,cumsum_R_16,ewm_B_10_6
12,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.058425,0.036071,0.001954,0.015163,0.550911,0.031931,0.064185,0.065115,0.05708,...,0.0,0.0,0.0,0.005608,0.079137,0.731084,0.004122,0.003347,0.061615,0.381153

In [47]:
# Merge all features into a single DataFrame using the 'customer_ID' column
df_one_id_merged = one_id_df_one_month.merge(
    one_id_df_ts, on='customer_ID', how='left'
).merge(
    one_id_df_tsfel, on='customer_ID', how='left'
)

In [48]:
df_one_id_merged.shape

(1, 432)

In [49]:
df_one_id_merged.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 432 columns):
 #    Column                           Dtype
---   ------                           -----
 0    customer_ID                      object
 1    S_2                              datetime64[ns]
 2    D_39                             float32
 3    B_1                              float32
 4    R_1                              float32
 5    B_4                              float32
 6    B_5                              float32
 7    R_2                              float32
 8    D_47                             float32
 9    B_7                              float32
 10   D_51                             float32
 11   B_9                              float32
 12   R_3                              float32
 13   B_10                             float32
 14   S_5                              float32
 15   B_11                             float32
 16   S_6                              float32
 17   R_4                              float32
 18   B_12                             float32
 19   S_8                              float32
 20   R_5                              float32
 21   D_58                             float32
 22   B_14                             float32
 23   D_60                             float32
 24   S_11                             float32
 25   D_65                             float32
 26   B_18                             float32
 27   S_12                             float32
 28   R_6                              float32
 29   S_13                             float32
 30   B_21                             float32
 31   D_71                             float32
 32   S_15                             float32
 33   B_23                             float32
 34   P_4                              float32
 35   D_75                             float32
 36   B_24                             float32
 37   R_7                              float32
 38   R_8                              float32
 39   S_16                             float32
 40   R_10                             float32
 41   R_11                             float32
 42   S_17                             float32
 43   R_12                             float32
 44   B_28                             float32
 45   R_13                             float32
 46   R_14                             float32
 47   R_15                             float32
 48   R_16                             float32
 49   S_18                             float32
 50   D_86                             float32
 51   R_17                             float32
 52   R_18                             float32
 53   B_31                             int64
 54   S_19                             float32
 55   R_19                             float32
 56   B_32                             float32
 57   S_20                             float32
 58   R_20                             float32
 59   R_21                             float32
 60   R_22                             float32
 61   R_23                             float32
 62   D_92                             float32
 63   D_93                             float32
 64   D_94                             float32
 65   R_24                             float32
 66   R_25                             float32
 67   D_96                             float32
 68   S_26                             float32
 69   D_102                            float32
 70   B_36                             float32
 71   B_37                             float32
 72   B_40                             float32
 73   D_127                            float32
 74   B_41                             float32
 75   D_133                            float32
 76   R_28                             float32
 77   D_140                            float32
 78   D_144                            float32
 79   target                           int64
 80   end_of_month                     datetime64[ns]
 81   D_126_-1.0                       float64
 82   D_126_0.0                        float64
 83   D_126_1.0                        float64
 84   D_126_nan                        float64
 85   D_63_CL                          float64
 86   D_63_CO                          float64
 87   D_63_CR                          float64
 88   D_63_XL                          float64
 89   D_63_XM                          float64
 90   D_63_XZ                          float64
 91   reverse_ewm_B_7_6                float64
 92   rolling_std_B_4_6                float64
 93   diff_B_4_10                      float32
 94   diff_B_4_9                       float32
 95   ewm_D_60_6                       float64
 96   diff_B_4_8                       float32
 97   diff_B_4_6                       float32
 98   diff_B_4_5                       float32
 99   diff_B_4_4                       float32
 100  diff_B_4_3                       float32
 101  rolling_mean_S_15_6              float64
 102  diff_B_4_2                       float32
 103  ewm_S_15_6                       float64
 104  expanding_max_B_4                float32
 105  ewm_R_1_6                        float64
 106  expanding_max_R_3                float32
 107  cummean_D_60                     float64
 108  cummean_R_1                      float64
 109  ewm_B_1_6                        float64
 110  cumsum_P_4                       float32
 111  cummean_P_4                      float64
 112  expanding_max_B_9                float32
 113  expanding_max_P_4                float32
 114  diff_B_9_2                       float32
 115  expanding_max_B_1                float32
 116  rolling_std_D_39_6               float64
 117  ewm_P_4_6                        float64
 118  diff_D_39_6                      float32
 119  diff_D_39_4                      float32
 120  diff_D_39_2                      float32
 121  expanding_max_D_39               float32
 122  expanding_max_R_1                float32
 123  cumsum_S_11                      float32
 124  expanding_max_S_15               float32
 125  cummean_S_15                     float64
 126  expanding_min_B_18               float32
 127  expanding_max_D_51               float32
 128  cumsum_B_18                      float32
 129  cummean_D_51                     float64
 130  cumsum_D_51                      float32
 131  ewm_D_65_6                       float64
 132  rolling_mean_D_65_6              float64
 133  ewm_D_47_6                       float64
 134  rolling_mean_D_47_6              float64
 135  expanding_max_D_47               float32
 136  expanding_min_D_47               float32
 137  cummean_D_47                     float64
 138  cumsum_D_47                      float32
 139  lag_D_47_3                       float32
 140  expanding_max_D_65               float32
 141  expanding_max_S_5                float32
 142  cummean_D_65                     float64
 143  cummean_R_3                      float64
 144  cumsum_R_3                       float32
 145  reverse_ewm_B_4_6                float64
 146  lag_B_5_1                        float32
 147  cummean_B_5                      float64
 148  expanding_min_B_5                float32
 149  ewm_S_8_6                        float64
 150  rolling_mean_B_5_6               float64
 151  reverse_ewm_B_5_6                float64
 152  cummean_R_2                      float64
 153  ewm_R_2_6                        float64
 154  lag_D_47_1                       float32
 155  lag_D_47_2                       float32
 156  cumsum_D_65                      float32
 157  ewm_B_5_6                        float64
 158  rolling_mean_S_8_6               float64
 159  ewm_D_39_6                       float64
 160  cummean_R_11                     float64
 161  rolling_std_D_75_6               float64
 162  expanding_max_D_102              float32
 163  ewm_R_5_6                        float64
 164  expanding_max_S_26               float32
 165  ewm_S_26_6                       float64
 166  cumsum_S_26                      float32
 167  lag_B_37_2                       float32
 168  ewm_B_7_6                        float64
 169  expanding_max_D_133              float32
 170  reverse_ewm_D_133_6              float64
 171  cummean_D_133                    float64
 172  rolling_mean_B_7_6               float64
 173  ewm_B_40_6                       float64
 174  rolling_std_B_40_6               float64
 175  expanding_max_B_40               float32
 176  expanding_max_D_75               float32
 177  diff_B_37_2                      float32
 178  expanding_max_S_8                float32
 179  cumsum_S_8                       float32
 180  ewm_R_11_6                       float64
 181  ewm_D_63_CR_6                    float64
 182  ewm_D_63_CO_6                    float64
 183  rolling_mean_D_63_CO_6           float64
 184  cumsum_D_63_CO                   float64
 185  lag_D_63_CO_2                    float64
 186  lag_D_63_CO_1                    float64
 187  expanding_min_B_28               float32
 188  diff_B_28_2                      float32
 189  ewm_D_51_6                       float64
 190  ewm_R_16_6                       float64
 191  rolling_mean_R_16_6              float64
 192  cumsum_R_16                      float32
 193  ewm_B_10_6                       float64
 194  R_10_Mean absolute deviation     float64
 195  R_5_Max                          float64
 196  D_126_1.0_Average power          float64
 197  D_102_Root mean square           float64
 198  B_9_Root mean square             float64
 199  B_9_Max                          float64
 200  B_9_Average power                float64
 201  R_5_Histogram mode               float64
 202  B_7_Root mean square             float64
 203  B_7_Max                          float64
 204  B_7_Average power                float64
 205  B_5_Root mean square             float64
 206  B_5_Mean absolute deviation      float64
 207  B_5_Mean                         float64
 208  S_5_ECDF Percentile_1            float64
 209  B_7_Mean                         float64
 210  B_5_Max                          float64
 211  D_133_Average power              float64
 212  D_133_Max                        float64
 213  D_47_Absolute energy             float64
 214  B_1_Average power                float64
 215  S_5_Max                          float64
 216  D_39_Standard deviation          float64
 217  D_39_Root mean square            float64
 218  D_39_Peak to peak distance       float64
 219  R_5_Average power                float64
 220  D_39_Mean                        float64
 221  D_39_Interquartile range         float64
 222  R_3_Root mean square             float64
 223  D_39_Average power               float64
 224  D_39_Absolute energy             float64
 225  D_144_Median absolute deviation  float64
 226  D_133_Root mean square           float64
 227  D_39_Max                         float64
 228  R_3_Mean                         float64
 229  B_5_ECDF Percentile_1            float64
 230  B_5_Absolute energy              float64
 231  S_15_Root mean square            float64
 232  B_23_Average power               float64
 233  B_1_Peak to peak distance        float64
 234  B_18_Histogram mode              float64
 235  B_1_Min                          float64
 236  B_1_Median                       float64
 237  B_23_Max                         float64
 238  B_1_Mean                         float64
 239  B_1_Max                          float64
 240  B_18_Median                      float64
 241  B_1_ECDF Percentile_1            float64
 242  B_18_Min                         float64
 243  B_1_ECDF Percentile_0            float64
 244  S_26_Max                         float64
 245  B_18_Mean                        float64
 246  B_5_Average power                float64
 247  S_15_Mean                        float64
 248  S_15_ECDF Percentile_0           float64
 249  B_4_Peak to peak distance        float64
 250  B_4_Median absolute deviation    float64
 251  B_4_Mean absolute deviation      float64
 252  B_4_Max                          float64
 253  S_11_Root mean square            float64
 254  B_4_ECDF Percentile_1            float64
 255  S_15_Max                         float64
 256  B_4_Absolute energy              float64
 257  B_40_ECDF Percentile_1           float64
 258  B_37_Root mean square            float64
 259  S_13_Root mean square            float64
 260  B_18_ECDF Percentile_0           float64
 261  S_15_Absolute energy             float64
 262  S_15_Average power               float64
 263  B_40_Max                         float64
 264  R_3_Max                          float64
 265  S_5_Mean                         float64
 266  S_5_Root mean square             float64
 267  D_65_Average power               float64
 268  D_65_Absolute energy             float64
 269  B_10_Min                         float64
 270  D_63_CR_Mean                     float64
 271  B_10_Root mean square            float64
 272  R_16_Interquartile range         float64
 273  D_65_Histogram mode              float64
 274  D_63_CR_Absolute energy          float64
 275  R_16_Mean absolute deviation     float64
 276  R_1_Average power                float64
 277  D_63_CO_ECDF Percentile_0        float64
 278  D_47_ECDF Percentile_0           float64
 279  D_63_CO_Absolute energy          float64
 280  R_1_Histogram mode               float64
 281  R_16_Mean                        float64
 282  D_65_Max                         float64
 283  D_65_Mean                        float64
 284  D_65_Mean absolute deviation     float64
 285  P_4_Median                       float64
 286  P_4_Mean                         float64
 287  P_4_Max                          float64
 288  B_10_ECDF Percentile_1           float64
 289  P_4_Histogram mode               float64
 290  S_8_Min                          float64
 291  P_4_Absolute energy              float64
 292  S_8_Median                       float64
 293  D_75_Standard deviation          float64
 294  S_8_Mean                         float64
 295  S_8_Max                          float64
 296  D_75_Max                         float64
 297  R_11_Mean                        float64
 298  D_65_Standard deviation          float64
 299  D_65_Peak to peak distance       float64
 300  R_1_Max                          float64
 301  R_1_Mean                         float64
 302  D_63_CO_Average power            float64
 303  R_1_Peak to peak distance        float64
 304  B_11_Median                      float64
 305  R_1_Mean absolute deviation      float64
 306  B_11_Min                         float64
 307  D_51_Histogram mode              float64
 308  B_11_Root mean square            float64
 309  R_3_Absolute energy              float64
 310  B_11_Standard deviation          float64
 311  R_3_Average power                float64
 312  D_51_Average power               float64
 313  S_8_Absolute energy              float64
 314  D_51_Absolute energy             float64
 315  D_47_Root mean square            float64
 316  D_47_Min                         float64
 317  D_47_Mean                        float64
 318  D_47_Max                         float64
 319  D_51_Median                      float64
 320  B_11_Mean                        float64
 321  D_51_Mean                        float64
 322  B_11_Max                         float64
 323  R_1_Root mean square             float64
 324  R_1_Standard deviation           float64
 325  D_60_Root mean square            float64
 326  R_2_Average power                float64
 327  D_60_Min                         float64
 328  D_58_Max                         float64
 329  D_51_Min                         float64
 330  D_51_Root mean square            float64
 331  B_10_Area under the curve        float64
 332  B_4_Sum absolute diff            float64
 333  B_5_Area under the curve         float64
 334  B_5_Mean absolute diff           float64
 335  B_5_Mean diff                    float64
 336  B_5_Median absolute diff         float64
 337  R_3_Mean absolute diff           float64
 338  B_7_Area under the curve         float64
 339  B_7_Mean diff                    float64
 340  R_3_Area under the curve         float64
 341  B_9_Area under the curve         float64
 342  R_2_Slope                        float64
 343  B_9_Mean diff                    float64
 344  B_9_Median diff                  float64
 345  B_9_Slope                        float64
 346  B_9_Sum absolute diff            float64
 347  R_2_Mean diff                    float64
 348  D_102_Area under the curve       float64
 349  B_4_Slope                        float64
 350  D_102_Median diff                float64
 351  B_4_Median diff                  float64
 352  B_4_Mean absolute diff           float64
 353  B_23_Slope                       float64
 354  B_24_Sum absolute diff           float64
 355  B_28_Mean diff                   float64
 356  B_28_Median diff                 float64
 357  S_11_Area under the curve        float64
 358  R_6_Mean diff                    float64
 359  B_37_Area under the curve        float64
 360  B_37_Mean diff                   float64
 361  B_37_Median diff                 float64
 362  R_5_Slope                        float64
 363  B_37_Positive turning points     float64
 364  B_37_Zero crossing rate          float64
 365  B_40_Area under the curve        float64
 366  R_5_Mean diff                    float64
 367  B_40_Mean absolute diff          float64
 368  B_4_Area under the curve         float64
 369  B_4_Centroid                     float64
 370  B_4_Mean diff                    float64
 371  R_2_Area under the curve         float64
 372  R_1_Slope                        float64
 373  D_126_1.0_Area under the curve   float64
 374  P_4_Area under the curve         float64
 375  D_75_Signal distance             float64
 376  D_60_Area under the curve        float64
 377  D_75_Mean diff                   float64
 378  D_75_Mean absolute diff          float64
 379  D_75_Area under the curve        float64
 380  D_65_Sum absolute diff           float64
 381  D_65_Slope                       float64
 382  D_65_Signal distance             float64
 383  D_63_CL_Slope                    float64
 384  D_65_Mean diff                   float64
 385  D_65_Mean absolute diff          float64
 386  D_63_CO_Area under the curve     float64
 387  D_63_CO_Centroid                 float64
 388  D_65_Area under the curve        float64
 389  D_63_CO_Mean diff                float64
 390  D_63_CR_Centroid                 float64
 391  P_4_Sum absolute diff            float64
 392  R_10_Mean absolute diff          float64
 393  D_51_Area under the curve        float64
 394  R_10_Slope                       float64
 395  R_1_Mean diff                    float64
 396  R_1_Mean absolute diff           float64
 397  R_1_Area under the curve         float64
 398  R_16_Slope                       float64
 399  D_133_Area under the curve       float64
 400  R_16_Mean absolute diff          float64
 401  D_133_Signal distance            float64
 402  R_16_Area under the curve        float64
 403  B_23_Positive turning points     float64
 404  D_144_Autocorrelation            float64
 405  D_144_Mean diff                  float64
 406  D_39_Area under the curve        float64
 407  D_39_Centroid                    float64
 408  D_39_Mean diff                   float64
 409  D_39_Signal distance             float64
 410  D_39_Slope                       float64
 411  D_47_Area under the curve        float64
 412  R_11_Area under the curve        float64
 413  D_144_Mean absolute diff         float64
 414  B_23_Mean diff                   float64
 415  B_5_Slope                        float64
 416  D_63_CO_Slope                    float64
 417  S_15_Area under the curve        float64
 418  S_26_Sum absolute diff           float64
 419  B_18_Area under the curve        float64
 420  S_26_Mean absolute diff          float64

In [50]:
cols = pd.read_parquet('../../data/final_features_ml/val_all_features_last_month.parquet').columns

In [51]:
cols

Index(['customer_ID', 'D_39', 'B_1', 'R_1', 'B_4', 'B_5', 'R_2', 'D_47', 'B_7',
       'D_51',
       ...
       'S_5_Signal distance', 'B_14_Mean diff', 'B_11_Mean diff',
       'S_8_Area under the curve', 'B_11_Area under the curve', 'S_8_Centroid',
       'B_1_Area under the curve', 'B_1_Mean diff',
       'S_26_Area under the curve', 'S_5_Area under the curve'],
      dtype='object', length=426)

In [52]:
df_one_id_merged[cols]

,customer_ID,D_39,B_1,R_1,B_4,B_5,R_2,D_47,B_7,D_51,...,S_5_Signal distance,B_14_Mean diff,B_11_Mean diff,S_8_Area under the curve,B_11_Area under the curve,S_8_Centroid,B_1_Area under the curve,B_1_Mean diff,S_26_Area under the curve,S_5_Area under the curve
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.009119,0.009382,0.006104,0.070793,0.231717,0.008309,0.539715,0.058425,0.673522,...,12.002586,-0.000679,0.000624,0.096573,0.000875,0.051362,0.00147,0.000055,0.00162,0.003494

In [ ]:
#Inference

In [52]:
#SHAP