In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df_last_month = pd.read_parquet('../../data/initial_modelling/train_X_data_last_month_oh.parquet').sort_values(by='customer_ID').reset_index(drop=True)
train_df_dl_features = pd.read_parquet('../../data/dl_features/exp_25_train_extracted.parquet')

In [3]:
train_df_last_month.head()

,customer_ID,D_39,B_1,R_1,B_4,B_5,R_2,D_47,B_7,D_51,...,R_28,D_140,D_144,D_63_CL,D_63_CO,D_63_CR,D_63_XL,D_63_XM,D_63_XZ,D_126_1.0
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.009119,0.009382,0.006104,0.070793,0.231717,0.008309,0.539715,0.058425,0.673522,...,0.002715,0.004234,0.002970,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,0.009704,0.004284,0.006450,0.031044,0.001557,0.001687,0.339125,0.026981,0.342118,...,0.007691,0.006623,0.000834,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,000084e5023181993c2e1b665ac88dbb1ce9ef621ec537...,0.009776,0.007853,0.006885,0.004432,0.012747,0.008217,1.053603,0.006804,0.003867,...,0.002873,0.007832,0.006943,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,000098081fde4fd64bc4d503a5d6f86a0aedc425c96f52...,0.000467,0.009413,0.007775,0.002541,0.006761,0.000599,0.016223,0.010545,0.005974,...,0.003672,0.005221,0.003703,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0000f99513770170a1aba690daeeb8a96da4a39f11fc27...,0.531173,0.979303,0.008500,1.105429,0.025943,0.003394,0.125423,0.998107,0.000275,...,0.003794,0.007061,0.003350,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [4]:
train_df_dl_features.head()

,DL_0,DL_1,DL_2,DL_3,DL_4,DL_5,DL_6,DL_7,DL_8,DL_9,DL_10,DL_11,DL_12,DL_13,DL_14,DL_15
0,6.894572,6.484050,0.000000,6.806992,0.000000,7.981942,6.737336,7.320887,0.000000,0.000000,0.000000,0.000000,6.951766,4.875103,7.235418,0.000000
1,6.679119,6.465893,0.000000,6.333076,0.000000,7.625560,6.486637,6.799274,0.000000,0.000000,0.000000,0.000000,7.007101,4.792603,6.760164,0.000000
2,3.606601,3.107703,0.000000,3.207478,0.000000,4.238704,3.384953,3.755443,0.000000,0.000000,0.000000,0.000000,3.777967,2.448155,3.791546,0.000000
3,1.138242,1.050633,0.000000,1.541710,0.000000,1.647928,1.205866,1.268733,0.000000,0.000000,0.000000,0.000000,1.247360,0.901859,1.331760,0.000000
4,0.000000,0.000000,1.944834,0.000000,1.209252,0.000000,0.000000,0.000000,1.523999,1.312626,1.391679,1.093533,0.000000,0.000000,0.000000,1.151772

In [5]:
train_df_last_month.shape, train_df_dl_features.shape

((289115, 85), (289115, 16))

In [6]:
train_df_dl_combined = pd.concat([train_df_last_month, train_df_dl_features], axis=1)
train_df_dl_combined.head()

,customer_ID,D_39,B_1,R_1,B_4,B_5,R_2,D_47,B_7,D_51,...,DL_6,DL_7,DL_8,DL_9,DL_10,DL_11,DL_12,DL_13,DL_14,DL_15
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.009119,0.009382,0.006104,0.070793,0.231717,0.008309,0.539715,0.058425,0.673522,...,6.737336,7.320887,0.000000,0.000000,0.000000,0.000000,6.951766,4.875103,7.235418,0.000000
1,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,0.009704,0.004284,0.006450,0.031044,0.001557,0.001687,0.339125,0.026981,0.342118,...,6.486637,6.799274,0.000000,0.000000,0.000000,0.000000,7.007101,4.792603,6.760164,0.000000
2,000084e5023181993c2e1b665ac88dbb1ce9ef621ec537...,0.009776,0.007853,0.006885,0.004432,0.012747,0.008217,1.053603,0.006804,0.003867,...,3.384953,3.755443,0.000000,0.000000,0.000000,0.000000,3.777967,2.448155,3.791546,0.000000
3,000098081fde4fd64bc4d503a5d6f86a0aedc425c96f52...,0.000467,0.009413,0.007775,0.002541,0.006761,0.000599,0.016223,0.010545,0.005974,...,1.205866,1.268733,0.000000,0.000000,0.000000,0.000000,1.247360,0.901859,1.331760,0.000000
4,0000f99513770170a1aba690daeeb8a96da4a39f11fc27...,0.531173,0.979303,0.008500,1.105429,0.025943,0.003394,0.125423,0.998107,0.000275,...,0.000000,0.000000,1.523999,1.312626,1.391679,1.093533,0.000000,0.000000,0.000000,1.151772

In [7]:
val_df_last_month = pd.read_parquet('../../data/initial_modelling/val_X_data_last_month_oh.parquet').sort_values(by='customer_ID').reset_index(drop=True)
val_df_dl_features = pd.read_parquet('../../data/dl_features/exp_25_val_extracted.parquet')

val_df_dl_combined = pd.concat([val_df_last_month, val_df_dl_features], axis=1)
val_df_dl_combined.head()

,customer_ID,D_39,B_1,R_1,B_4,B_5,R_2,D_47,B_7,D_51,...,DL_6,DL_7,DL_8,DL_9,DL_10,DL_11,DL_12,DL_13,DL_14,DL_15
0,0006a80d96aec1d178bf74adab6cbf9e4bf427a6ba264f...,0.186344,0.054017,0.009121,0.159391,0.004153,0.002819,0.196100,0.222227,0.005456,...,0.000000,0.000000,1.110735,0.708074,0.931448,0.595479,0.000000,0.000000,0.000000,0.783689
1,000b789efc34ef75106b9e135dbeabd0408e0735fa8b2d...,0.003092,0.007243,0.009337,0.058368,0.012688,0.004526,0.634168,0.041067,0.335320,...,5.006511,5.400367,0.000000,0.000000,0.000000,0.000000,5.437877,3.900988,5.449194,0.000000
2,000f8675ede66cc6affd4c048db11a00246d7ee623f453...,0.009306,0.004754,0.005596,0.007301,0.004718,0.002971,0.395201,0.006074,0.009784,...,4.251059,4.530725,0.000000,0.000000,0.000000,0.000000,4.512188,3.168711,4.593558,0.000000
3,0014eef7b7aefc114ea48847275fe8e5c14455e5adb43a...,0.005589,0.035921,0.003313,0.221453,0.084993,0.007096,0.377228,0.170150,0.674746,...,3.954748,4.305258,0.000000,0.000000,0.000000,0.000000,4.441238,3.117230,4.063981,0.000000
4,0016b9485e459e660a7b05fa1df47c5e206bb3e62836b9...,0.001006,0.008405,0.005972,0.115843,0.007564,0.005676,0.347962,0.053727,0.005466,...,2.026786,2.129326,0.000000,0.000000,0.000000,0.000000,2.546600,1.503630,2.158355,0.000000

In [8]:
test_df_last_month = pd.read_parquet('../../data/initial_modelling/test_X_data_last_month_oh.parquet').sort_values(by='customer_ID').reset_index(drop=True)
test_df_dl_features = pd.read_parquet('../../data/dl_features/exp_25_test_extracted.parquet')

test_df_dl_combined = pd.concat([test_df_last_month, test_df_dl_features], axis=1)
test_df_dl_combined.head()

,customer_ID,D_39,B_1,R_1,B_4,B_5,R_2,D_47,B_7,D_51,...,DL_6,DL_7,DL_8,DL_9,DL_10,DL_11,DL_12,DL_13,DL_14,DL_15
0,00000fd6641609c6ece5454664794f0340ad84dddce9a2...,0.178126,0.034684,0.006911,0.020626,0.027000,0.004976,0.402195,0.028411,0.339683,...,5.764231,6.173485,0.000000,0.00000,0.000000,0.000000,6.153308,4.215621,6.063298,0.000000
1,000041bdba6ecadd89a52d11886e8eaaec9325906c9723...,0.001083,0.012564,0.007829,0.007235,0.118818,0.004238,0.414224,0.011969,0.333342,...,4.509210,4.714250,0.000000,0.00000,0.000000,0.000000,4.894351,3.420918,4.600852,0.000000
2,00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...,0.005573,0.007679,0.001247,0.269407,0.004855,0.001991,0.480303,0.159818,0.003557,...,3.706461,3.885978,0.000000,0.00000,0.000000,0.000000,4.245215,2.843341,3.793341,0.000000
3,0000d17a1447b25a01e42e1ac56b091bb7cbb06317be4c...,0.006181,-0.000886,0.006112,0.051335,0.063894,0.009902,0.522748,0.073910,0.005355,...,5.021643,5.275514,0.000000,0.00000,0.000000,0.000000,5.387375,3.880430,5.249128,0.000000
4,00013181a0c5fc8f1ea38cd2b90fe8ad2fa8cad9d9f13e...,0.009807,0.090679,0.507561,0.631626,0.002904,1.007081,0.346709,0.849623,0.009915,...,0.000000,0.000000,2.390673,1.96816,2.084374,1.777916,0.000000,0.000000,0.000000,1.780722

In [9]:
train_df_dl_combined.to_parquet('../../data/last_month_and_dl_features/train_X_data_last_month_and_dl_features.parquet', index=False)
val_df_dl_combined.to_parquet('../../data/last_month_and_dl_features/val_X_data_last_month_and_dl_features.parquet', index=False)
test_df_dl_combined.to_parquet('../../data/last_month_and_dl_features/test_X_data_last_month_and_dl_features.parquet', index=False)